import { Router } from 'express';
import { alertasRouter } from './modules/alertas/alertas.routes.js';
import { authRouter } from './modules/auth/auth.routes.js';
import { categoriasPeajeRouter } from './modules/categorias-peaje/categorias-peaje.routes.js';
import { cierresSemanalesRouter } from './modules/cierres-semanales/cierres-semanales.routes.js';
import { clientesRouter } from './modules/clientes/clientes.routes.js';
import { conductoresRouter } from './modules/conductores/conductores.routes.js';
import { healthRouter } from './modules/health/health.routes.js';
import { mantenimientosRouter } from './modules/mantenimientos/mantenimientos.routes.js';
import { peajesRouter } from './modules/peajes/peajes.routes.js';
import { propietariosRouter } from './modules/propietarios/propietarios.routes.js';
import { reportesRouter } from './modules/reportes/reportes.routes.js';
import { reportesSemanalesRouter } from './modules/reportes-semanales/reportes-semanales.routes.js';
import { rolesRouter } from './modules/roles/roles.routes.js';
import { rutasRouter } from './modules/rutas/rutas.routes.js';
import { rutasPeajesRouter } from './modules/rutas-peajes/rutas-peajes.routes.js';
import { tarifasPeajeRouter } from './modules/tarifas-peaje/tarifas-peaje.routes.js';
import { tarifasRutaRouter } from './modules/tarifas-ruta/tarifas-ruta.routes.js';
import { tiposCargaRouter } from './modules/tipos-carga/tipos-carga.routes.js';
import { tiposGastoViajeRouter } from './modules/tipos-gasto-viaje/tipos-gasto-viaje.routes.js';
import { tiposMantenimientoRouter } from './modules/tipos-mantenimiento/tipos-mantenimiento.routes.js';
import { usuariosRouter } from './modules/usuarios/usuarios.routes.js';
import { usuariosPropietariosRouter } from './modules/usuarios-propietarios/usuarios-propietarios.routes.js';
import { vehiculosRouter } from './modules/vehiculos/vehiculos.routes.js';
import { viajesRouter } from './modules/viajes/viajes.routes.js';

export const apiRouter = Router();

apiRouter.use('/health', healthRouter);
apiRouter.use('/alertas', alertasRouter);
apiRouter.use('/auth', authRouter);
apiRouter.use('/categorias-peaje', categoriasPeajeRouter);
apiRouter.use('/cierres-semanales', cierresSemanalesRouter);
apiRouter.use('/clientes', clientesRouter);
apiRouter.use('/conductores', conductoresRouter);
apiRouter.use('/mantenimientos', mantenimientosRouter);
apiRouter.use('/peajes', peajesRouter);
apiRouter.use('/propietarios', propietariosRouter);
apiRouter.use('/reportes', reportesRouter);
apiRouter.use('/reportes-semanales', reportesSemanalesRouter);
apiRouter.use('/roles', rolesRouter);
apiRouter.use('/rutas', rutasRouter);
apiRouter.use('/rutas-peajes', rutasPeajesRouter);
apiRouter.use('/tarifas-peaje', tarifasPeajeRouter);
apiRouter.use('/tarifas-ruta', tarifasRutaRouter);
apiRouter.use('/tipos-carga', tiposCargaRouter);
apiRouter.use('/tipos-gasto-viaje', tiposGastoViajeRouter);
apiRouter.use('/tipos-mantenimiento', tiposMantenimientoRouter);
apiRouter.use('/usuarios', usuariosRouter);
apiRouter.use('/usuarios-propietarios', usuariosPropietariosRouter);
apiRouter.use('/vehiculos', vehiculosRouter);
apiRouter.use('/viajes', viajesRouter);
